[package]
name = "open-timeline-games"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = "OpenTimeline games"
repository = "https://github.com/harryhudson/open-timeline"
homepage = "https://github.com/harryhudson/open-timeline"

# Needed for wasm-bindgen to work
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
open-timeline-core = { workspace = true }

bool-tag-expr = { version = "0.1.0-beta.2" }
console_error_panic_hook = "0.1.7"
console_log = "1.0"
log = "0.4.25"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
thiserror = "2.0.11"
rand = "0.8.5"

getrandom = { version = "0.2.17", features = ["js"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = [
    "console",
    "CanvasRenderingContext2d",
    "CssStyleDeclaration",
    "Document",
    "DomStringMap",
    "Element",
    "HtmlElement",
    "HtmlButtonElement",
    "HtmlCanvasElement",
    "HtmlDivElement",
    "HtmlInputElement",
    "HtmlSelectElement",
    "HtmlSpanElement",
    "ImageData",
    "KeyboardEvent",
    "MouseEvent",
    "Node",
    "NodeList",
    "TouchEvent",
    "TouchList",
    "Touch",
    "TextMetrics",
    "WheelEvent",
    "Window",
] }
